s, t = gets.strip.split(" ").map(&:to_i)
a, b = gets.strip.split(" ").map(&:to_i)
m, n = gets.strip.split(" ").map(&:to_i)
apples = gets.strip.split(" ").map(&:to_i)
oranges = gets.strip.split(" ").map(&:to_i)
puts(apples.select{|x| a+x>=s and a+x<=t}.length,oranges.select{|x| b+x>=s and b+x<=t}.length)
